### ISSUE TITLE
Task: Store student data into database when access code is requested.

### ISSUE THREAD

**Issue by JustinHenderson98** [snmackay/CSE-442#34]
TEST:
1. check tethys : Database: cse442_542_2019_summer_teame_db  to see if passcode and timestamp have been updated on existing student.
2. check tethys : Database: cse442_542_2019_summer_teame_db to see if new student has been added with passcode and timestamp.

**Comment by snmackay** [comment]
Notes:
1. connect to tethys : Database: cse442_542_2019_summer_teame_db.
2. update passcode and timestamp first in student_login.
2. insert into student_login if update fails.
