### ISSUE TITLE
TASK: Create a system that sends an email code to the student on submission of email address.

### ISSUE THREAD

**Issue by JustinHenderson98** [snmackay/CSE-442#7]
aSSOCIATED USER STORY: #1
ASSOCIATED BRANCH: loginPageBackend
Steps planned:
Create a text box that accepts the email address.
Create a button that sends a post request to the server.
Check that email is a school email.
Hash email address and send code to email address provided.
Test: email will contain a unique code each time that request is sent.

**Comment by snmackay** [comment]
TEST:
1: Type in a UB email address into the textbox at https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442e/ 
2: Ensure an email containing the appropriate code '4567890' is received by the same email address.
